apiVersion: v1
kind: PersistentVolume
metadata:
  name: atreadapi-pv
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/sinsakuokazaki/Project/atread/app"